version: '3'
services:
  login-app:
    build:
      context: .
      dockerfile: Dockerfile.app
    restart: on-failure
    networks:
      - login-network

  login-nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: on-failure
    ports:
      - "10001:80"
    networks:
      - login-network

networks:
  login-network:
    driver: bridge