version: '3.2'
services:
 wangy-app:
   build:
     context: .
     dockerfile: Dockerfile.app
   restart: on-failure
   networks:
     - wangy-network

  wangy-nginx:
   build:
     context: .
     dockerfile: Dockerfile.nginx
   restart: on-failure
   ports:
     - "11011:80"
   networks:
     - wangy-network

networks:
  wangy-network:
    driver: overlay
    attachable: true